name: Build with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:  
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
        java-version: [ 1.8 ]

    runs-on: ${{ matrix.platform }}
    env:
      PLATFORM: ${{ matrix.platform }}
      JAVA_VERSION: ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
                "id": "github-packages",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]
          properties: |
            [
              { "maven.wagon.http.ssl.insecure": "true" },
              { "maven.wagon.http.ssl.allowall": "true" },
              { "maven.wagon.http.ssl.ignore.validity.dates": "true"}
            ]
          githubServer: false      
      
      - name: Build with Maven
        run: mvn -P github-packages --batch-mode install
      
      - name: Publish package
        run: mvn -P github-packages -DskipTests -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'release' && github.event.action == 'created' && matrix.os == 'ubuntu-latest'
